version: '3.9'

services:
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    networks:
      - network
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d db -U user']
      interval: 15s
      timeout: 10s
      retries: 10
    command: ['postgres', '-c', 'log_statement=all']

networks:
  network:
    driver: bridge
